//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Item
    {
        public string Cake_ID { get; set; }
        public int Cart_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Orther { get; set; }
    
        public virtual Cake Cake { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
