//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            this.Cart_Item = new HashSet<Cart_Item>();
        }
    
        public string Customer_ID { get; set; }
        public int Cart_ID { get; set; }
        public string Customer_Payment_ID { get; set; }
        public Nullable<System.DateTime> Payment_time { get; set; }
        public string Shipping_Address { get; set; }
        public string Customer_Requirements { get; set; }
        public Nullable<int> Cart_Status { get; set; }
        public Nullable<double> Total { get; set; }
        public string Driver_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_Item> Cart_Item { get; set; }
    }
}
