//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int Comment_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Cake_ID { get; set; }
        public Nullable<System.DateTime> Time_comment { get; set; }
        public string Content { get; set; }
    
        public virtual Cake Cake { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
