//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Payment_Methods
    {
        public string Customer_Payment_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Payment_Menthod_Code { get; set; }
        public string Card_Number { get; set; }
        public string Date_from { get; set; }
        public string Date_to { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment_Methods Payment_Methods { get; set; }
    }
}
