//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class H_TshopEntities : DbContext
    {
        public H_TshopEntities()
            : base("name=H_TshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cake_Image> Cake_Image { get; set; }
        public virtual DbSet<Cake_Type> Cake_Type { get; set; }
        public virtual DbSet<Cake> Cakes { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart_Item> Cart_Item { get; set; }
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Payment_Methods> Customer_Payment_Methods { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<LoginSystem> LoginSystems { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Payment_Methods> Payment_Methods { get; set; }
    }
}
