//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSystem
    {
        public string ID { get; set; }
        public string Pass { get; set; }
        public Nullable<int> ID_Rule { get; set; }
    
        public virtual Chef Chef { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
