//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweepCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string Manager_ID { get; set; }
        public string Manager_Name { get; set; }
        public string Manager_Phone { get; set; }
    
        public virtual LoginSystem LoginSystem { get; set; }
    }
}
